# Generated by Django 4.2 on 2024-06-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('course_time', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('demo_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('img', models.ImageField(upload_to='portofolio/images/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project_tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='portofolio/images/')),
                ('link', models.URLField(blank=True)),
                ('projects', models.ManyToManyField(through='portofolio.Project_tool', to='portofolio.project')),
            ],
        ),
        migrations.AddField(
            model_name='project_tool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.tool'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(through='portofolio.Project_tool', to='portofolio.tool'),
        ),
    ]
